# Generated by Django 5.1.6 on 2025-12-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_add_goa_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget per person in USD', max_digits=10, null=True),
        ),
    ]
